version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum install terraform -y

  build:
    commands:
      - export TF_VAR_sonarurl=$sonarqubeurl
      - export TF_VAR_sonartoken=$sonarqubetoken
      - cd "$CODEBUILD_SRC_DIR/devops/terraform"
      - terraform init 
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '$CODEBUILD_SRC_DIR/**'